services:
  - type: web
    name: subscription-service
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn subscription_service.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: ALLOWED_HOSTS
        value: "human-x.onrender.com,localhost,127.0.0.1"
      - key: DATABASE_URL
        fromDatabase:
          name: subscription_db
          property: connectionString
      - key: MONGODB_URI
        value: "mongodb+srv://aswins:Humanx@cluster0.hvjdv.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
      - key: STRIPE_PUBLIC_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: SUBSCRIPTION_CURRENCY
        value: "usd"

databases:
  - name: subscription_db
    databaseName: subscription
    user: subscription_user 