# Generated by Django 5.2 on 2025-04-16 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pdf_generated', models.BooleanField(default=False)),
                ('pdf_path', models.CharField(blank=True, max_length=255, null=True)),
                ('email_sent', models.BooleanField(default=False)),
            ],
        ),
    ]
